#!/bin/bash

# Copyright (C) NublaII <https://stackoverflow.com/users/1360859/nublaii>

# Directory you want to watch
WATCHDIR="${1:-}"
# Check directory track valid
if [ ! -d "$WATCHDIR" ];
then
    echo "Directory is not exists !"
    exit
fi
WORKINGDIR="$WATCHDIR/.tracked"
# Create directory .tracked
mkdir -p "$WORKINGDIR"
# Name of the file that will keep the list of the files when you last checked it
LAST="$WORKINGDIR/last"
# Name of the file that will keep the list of the files you are checking now
CURRENT="$WORKINGDIR/current"
LASTWATCHED="$WORKINGDIR/lastwatch"
# The first time we create the log file
touch "$LAST"

if [ -f "$LASTWATCHED" ];
then
    echo "Check file changed or created never `cat "$LASTWATCHED"`"
    find "$WATCHDIR" -cnewer "$LASTWATCHED" -type f ! -path "$WORKINGDIR/*" > "$CURRENT"
else
    find "$WATCHDIR" -type f ! -path "$WORKINGDIR/*" > "$CURRENT"
fi
echo "`date +"%FT%T%z"`" > "$LASTWATCHED"
diff "$LAST" "$CURRENT" > /dev/null 2>&1

# If there is no difference exit
if [ $? -eq 0 ]
then
    echo -e "\033[1;32mNo changes\033[0m"
else
    # Else, list the files that changed
    echo -e "\033[0;32mList of new files\033[0m"
    diff "$LAST" "$CURRENT" | grep '^>' | awk -F '> ' '{print $2}'
    echo -e "\033[0;31mList of files removed\033[0m"
    diff "$LAST" "$CURRENT" | grep '^<' | awk -F '< ' '{if(system("[ ! -f " $2 " ]") == 0) { print $2}}'

    # Lastly, move CURRENT to LAST
    mv "$CURRENT" "$LAST"
fi
